sources:
  pokedex:
    url: https://www.kaggle.com/api/v1/datasets/download/noeyislearning/pokdex
    output:
      folder_name: downloads/pokedex
      schema_name: pokedex
  movies:
    url: https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?select=movies_metadata.csv
  netflix:
    url: https://www.kaggle.com/datasets/victorsoeiro/netflix-tv-shows-and-movies?select=titles.csv
  wdi:
    url: https://www.kaggle.com/datasets/kaggle/world-development-indicators
  european_soccer:
    url: https://www.kaggle.com/datasets/hugomathien/soccer
  retail_rocket:
    url: https://www.kaggle.com/datasets/retailrocket/ecommerce-dataset?select=item_properties_part1.csv
  amazon:
    url: https://www.kaggle.com/datasets/datafiniti/consumer-reviews-of-amazon-products?select=Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv
  taxi:
    url: https://www.kaggle.com/datasets/atmarouane/nyc-taxi-trip-noisy
  google_play_store:
    url: https://www.kaggle.com/datasets/lava18/google-play-store-apps?select=googleplaystore.csv
  instacart:
    url: https://www.kaggle.com/datasets/psparks/instacart-market-basket-analysis?select=products.csv
